server:
  port: 9003

spring:
  application:
    name: nacos-consumer-order

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 # 采样值介于0到1之间，1表示全部采集
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8088 #配置sentinel dashboard地址
        port: 8719 #  默认8719端口,加入被占用会自动从8719开始一次+1扫描,直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-provider-payment

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
