server:
  port: 3344


eureka:
  client:
    register-with-eureka: true #true 表示将自己注册进EurekaServer
    fetch-registry: true #true 表示抓取已有注册信息，职责是维护实例，并不需要去检索服务
    service-url:
      #      设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://ethan-primary.com:7001/eureka/,http://ethan-secondary.com:7002/eureka/
  instance:
    instance-id: configServer
    prefer-ip-address: true #访问路径可以显示IP地址
    #    Eureka客户端向服务端发送心跳的时间间隔，默认30S
    lease-expiration-duration-in-seconds: 10
    #   Eureka服务端在收到最后一次心跳后等待时间上限，单位默认90S，超时即剔除服务
    lease-renewal-interval-in-seconds: 20

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PhotonAlpha/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
#      添加配置信息
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
#    RabbitMQ相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
