server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/my-cloud?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    zookeeper:
      connect-string: ethan-primary.com:2181
