server:
  port: 7002

eureka:
  instance:
    hostname: ethan-secondary.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false #fasle 表示自己就是注册中心，职责是维护实例，并不需要去检索服务
    service-url:
#      设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://ethan-primary.com:7001/eureka/
  server:
    #    关闭自我保护机制，保证不可用服务及时被剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

