server:
  port: 8802


eureka:
  client:
    register-with-eureka: true #true 表示将自己注册进EurekaServer
    fetch-registry: true #true 表示抓取已有注册信息，职责是维护实例，并不需要去检索服务
    service-url:
      #      设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://ethan-primary.com:7001/eureka/,http://ethan-secondary.com:7002/eureka/
  instance:
    instance-id: streamConsumerServer:8802
    prefer-ip-address: true #访问路径可以显示IP地址
    #    Eureka客户端向服务端发送心跳的时间间隔，默认30S
    lease-expiration-duration-in-seconds: 10
    #   Eureka服务端在收到最后一次心跳后等待时间上限，单位默认90S，超时即剔除服务
    lease-renewal-interval-in-seconds: 20

spring:
  application:
    name: cloud-consumer-provider
  cloud:
    stream:
      binders:
        defaultRabbit: # 在此处配置要绑定的rabbit mq的服务信息
          type: rabbit #消息组件类型
          environment: #设置rabbitmq相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用exchange名称定义
          content-type: application/json #设置消息类型，本次为json，文本则设置“text/plain”
          binderd: defaultRabbit #设置要绑定的消息服务的具体设置
#          group: groupA
